version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/github-mcp-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - >
        -s -w 
        -X main.Version={{ .Version }}
        -X main.Commit={{ .Commit }}
        -X main.Date={{ .Date }}

archives:
  - name_template: "{{ .Os }}-{{ .Arch }}"
    format: binary

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  use: github-native

release:
  draft: false