on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Tag for the release'
        required: true
      draft_release:
        description: 'Create a draft release'
        required: false
        default: false
      

permissions:
  contents: write
  id-token: write
  attestations: write

env:
  SOURCE_REPO: github/github-mcp-server
  VERSION_TAG: ${{ github.event.inputs.tag }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.SOURCE_REPO }}
          ref: ${{ github.event.inputs.release_tag }}
          path: source
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "source/go.mod"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552
        with:
          distribution: goreleaser
          # GoReleaser version
          version: "~> v2"
          # Arguments to pass to GoReleaser
          args: release --clean --config ../goreleaser.yaml
          workdir: ./source
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      