on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag to release'
        required: true
      pattern:
        description: 'Pattern to match release artifacts'
        default: 'gh-extension-*'

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ github.token }}
  SOURCE_REPO: github/github-mcp-server
  VERSION_TAG: ${{ github.event.inputs.tag }}
  PATTERN: ${{ github.event.inputs.pattern }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get release artifacts
        id: get_release_artifacts
        run:
          gh release download --repo ${{ env.SOURCE_REPO }}  --pattern ${{ env.PATTERN }}
      - name: Create release
        id: create_release
        run: |
          gh release create ${{ env.VERSION_TAG }} --title "${{ env.VERSION_TAG }}" --notes "Release ${{ env.VERSION_TAG }}"
          gh release upload ${{ env.VERSION_TAG }} --clobber ${{ env.PATTERN }}