on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Tag for the release'
        required: true
      draft_release:
        description: 'Create a draft release'
        required: false
        default: false
      

permissions:
  contents: write
  id-token: write
  attestation: write

env:
  GITHUB_TOKEN: ${{ github.token }}
  SOURCE_REPO: github/github-mcp-server
  VERSION_TAG: ${{ github.event.inputs.tag }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.SOURCE_REPO }}
      - uses: cli/gh-extension-precompile@v2
        with:
          release_title_prefix: 'GitHub MCP Server - GitHub CLI Extension '
          go_version_file: go.mod
          draft_release: ${{ github.event.inputs.draft_release }}
          generate_attestations: true